"""Airflow MCP — Model Context Protocol server for Apache Airflow 2.x and 3.x."""

from __future__ import annotations

try:
    # Generated by `hatch-vcs` at build time from the nearest git tag.
    # Provides a real PEP 440 version string in installed wheels and sdists.
    from airflow_mcp._version import __version__
except ImportError:  # pragma: no cover — editable install or source checkout
    # Fallback for `uv run` / `python -m` from a source tree before any
    # build step has generated _version.py. Uses a dev marker.
    __version__ = "0.2.0+unknown"

__all__ = ["__version__"]
